#
# Run the docker compose command from the project's root folder to build / start.
#
# I.e:
#    cd __project_root_dir
#    docker compose --env-file .env -f docker/compose.yaml --project-directory docker up --build
#
# To populate the databse
#     docker exec -i container_name mysql -uroot -ppassword db_name < db.sql

version: '3.8'
services:
    db:
        image: mariadb:11.0.3-jammy
        command: --default-authentication-plugin=mariadb_native_password
        volumes:
            - ../database/lib:/var/lib/mysql
            - ./my.cnf:/etc/mysql/my.cnf
            - ../database/db_initial.sql.gz:/db_initial.sql.gz
            - ../database/_mariadb_init.sh:/docker-entrypoint-initdb.d/_init.sh
        environment:
            - MARIADB_CONTAINER_USER=${uid}
            - MARIADB_CONTAINER_GROUP=${gid}
            - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MARIADB_USER=${DB_USER}
            - MARIADB_PASSWORD=${DB_PASSWORD}
            - MARIADB_DATABASE=${DB_NAME}
        ports:
            - 3306:3306
        restart: unless-stopped

    # db:
    #     image: mysql:5.7
    #     command: --default-authentication-plugin=mysql_native_password
    #     volumes:
    #         - ../database/lib:/var/lib/mysql
    #         - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    #         - ./my.cnf:/etc/mysql/my.cnf
    #         - ../database/db_initial.sql:/db_initial.sql
    #         #- ../database/_init.sh:/docker-entrypoint-initdb.d/_init.sh
    #     environment:
    #         - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    #         - MYSQL_DATABASE=${DB_NAME}
    #         - MYSQL_USER=${DB_USER}
    #         - MYSQL_PASSWORD=${DB_PASSWORD}
    #     ports:
    #         - 3306:3306
    #     restart: unless-stopped

    jboss:
        image: nloyola/biobank:0.1
        working_dir: '/opt/biobank'
        command: sh -c "/opt/jboss/bin/run.sh"
        depends_on:
            - db
        environment:
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_NAME=${DB_NAME}
            - JBOSS_HOME=/opt/jboss
            - JAVA_HOME=/opt/jdk/jdk1.6.0_45
            - JAVA=/opt/jdk/jdk1.6.0_45/bin/java
            - JBOSS_LOG_DIR=/var/log/jboss
            - ANT_HOME=/opt/apache-ant-1.9.0
        restart: unless-stopped
        ports:
            - 8080:8080

    frontend:
        image: node:18-alpine
        user: '${uid}:${gid}'
        working_dir: '/opt/biobank/frontend'
        volumes:
            - ../frontend:/opt/biobank/frontend
        command: sh -c "npm install && npm run dev"
        environment:
            - BACKEND_SERVER=host.docker.internal:9000
        ports:
            - 3000:3000
        restart: unless-stopped
        extra_hosts:
                - "host.docker.internal:host-gateway"
