#
# Run the docker compose command from the project's root folder to build / start.
#
# I.e:
#    cd __project_root_dir
#    docker compose --env-file .env -f docker/compose.dev.yaml --project-directory docker up --build
#

version: '3.9'
services:
    db:
        extends:
            file: compose.yaml
            service: db
        ports:
            - 3306:3306

    jboss:
        extends:
            file: compose.yaml
            service: jboss
        depends_on:
            - db
        ports:
            - 8080:8080

    # app:
    #     build:
    #         context: ../
    #         dockerfile: Dockerfile
    #     image: app-image
    #     command: sh -c "/app/mvnw clean spring-boot:run"
    #     working_dir: /app
    #     volumes:
    #        - ../src:/app/src
    #     ports:
    #         - 9000:9000
    #         - 35729:35729
    #     depends_on:
    #         - db
    #     environment:
    #        - DB_HOST=db
    #        - DB_NAME=$DB_NAME
    #        - DB_USER=$DB_USER
    #        - DB_PASSWORD=$DB_PASSWORD

    frontend:
        image: node:18-alpine
        user: '${uid}:${gid}'
        working_dir: '/opt/biobank/frontend'
        volumes:
            - ../frontend:/opt/biobank/frontend
        command: sh -c "npm install && npm run dev"
        environment:
            - BACKEND_SERVER=http://host.docker.internal:9000
        ports:
            - 3000:3000
        restart: unless-stopped
        extra_hosts:
            - "host.docker.internal:host-gateway"
