#
# Run the docker compose command from the project's root folder to build / start.
#
# I.e:
#    cd __project_root_dir
#    docker compose --env-file .env -f docker/compose.dev.yaml --project-directory docker up --build
#

version: '3.9'
services:
    db:
        extends:
            file: compose.yaml
            service: db
        ports:
           - 3306:3306

    jboss:
        extends:
            file: compose.yaml
            service: jboss
        ports:
            - 8080:8080

    frontend:
        image: node:18-alpine
        user: '${uid}:${gid}'
        working_dir: '/opt/biobank/frontend'
        volumes:
            - ../frontend:/opt/biobank/frontend
        command: sh -c "npm install && npm run dev"
        environment:
            - BACKEND_SERVER=host.docker.internal:9000
        ports:
            - 3000:3000
        restart: unless-stopped
        extra_hosts:
                - "host.docker.internal:host-gateway"
